dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    version: 0.6.12
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

networks:
  mainnet-fork:
    eth_usd: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'